# Site settings
title: Iron Horse Fitness
email: ironhorsefitnessllc@gmail.com
address: 115 Railroad Ave. Danville, CA 94526
description: Iron Horse Fitness Training Gym
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ironhorsefitness.github.io" # the base hostname & protocol for your site

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 3

# Misc settings
featured-image-source:

# Social settings
500px_url:
facebook_url:
instagram_url:
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown

sass:
  style: compressed
